import { useState, useEffect } from 'react';
import { X, Upload, Loader2 } from 'lucide-react';
import { supabase } from '../../lib/supabase';
import type { LedgerEntry } from './LedgerTable';

interface AddEntryModalProps {
    isOpen: boolean;
    onClose: () => void;
    onAdd: (entry: LedgerEntry) => void;
    onUpdate?: (entry: LedgerEntry) => void;
    initialData?: LedgerEntry | null;
}

export default function AddEntryModal({ isOpen, onClose, onAdd, onUpdate, initialData }: AddEntryModalProps) {
    const [date, setDate] = useState('');
    const [category, setCategory] = useState('');
    const [item, setItem] = useState('');
    const [vendor, setVendor] = useState('');
    const [cost, setCost] = useState('');
    const [file, setFile] = useState<File | null>(null);
    const [isSubmitting, setIsSubmitting] = useState(false);

    // Reset or populate form when modal opens or initialData changes
    useEffect(() => {
        if (isOpen) {
            if (initialData) {
                setDate(initialData.date);
                setCategory(initialData.category);
                setItem(initialData.item);
                setVendor(initialData.vendor);
                setCost(initialData.cost.toString());
                setFile(null); // Reset file input
            } else {
                setDate(new Date().toISOString().split('T')[0]);
                setCategory('General');
                setItem('');
                setVendor('');
                setCost('');
                setFile(null);
            }
        }
    }, [isOpen, initialData]);

    if (!isOpen) return null;

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        setIsSubmitting(true);

        try {
            let receipt_url = initialData?.receipt_url;
            let receipt_filename = initialData?.receipt_filename;

            if (file) {
                const fileExt = file.name.split('.').pop();
                const fileName = `${Date.now()}_${Math.random().toString(36).substring(7)}.${fileExt}`;
                const filePath = `${fileName}`;

                const { error: uploadError } = await supabase.storage
                    .from('receipts')
                    .upload(filePath, file);

                if (uploadError) throw uploadError;

                const { data: { publicUrl } } = supabase.storage
                    .from('receipts')
                    .getPublicUrl(filePath);

                receipt_url = publicUrl;
                receipt_filename = file.name;
            }

            const costNum = parseFloat(cost);

            if (initialData && onUpdate) {
                // UPDATE EXISTING
                const updatedEntry: LedgerEntry = {
                    ...initialData,
                    date,
                    category,
                    item,
                    vendor,
                    cost: costNum,
                    receipt_url,
                    receipt_filename
                };

                await onUpdate(updatedEntry);
            } else {
                // CREATE NEW
                const newEntry = {
                    // id will be generated by Supabase
                    date,
                    category,
                    item,
                    vendor,
                    cost: costNum,
                    receipt_url,
                    receipt_filename
                };

                const { data, error } = await supabase
                    .from('ledger_entries')
                    .insert([newEntry])
                    .select()
                    .single();

                if (error) throw error;
                onAdd(data);
                onClose();
            }
        } catch (error) {
            console.error('Error submitting form:', error);
            alert('Failed to save entry. Please try again.');
        } finally {
            setIsSubmitting(false);
        }
    };

    return (
        <div className="fixed inset-0 z-50 overflow-y-auto">
            <div className="flex items-center justify-center min-h-screen pt-4 px-4 pb-20 text-center sm:block sm:p-0">
                <div className="fixed inset-0 transition-opacity" aria-hidden="true">
                    <div className="absolute inset-0 bg-gray-500 opacity-75 mr-0" onClick={onClose}></div>
                </div>

                <span className="hidden sm:inline-block sm:align-middle sm:h-screen" aria-hidden="true">&#8203;</span>

                <div className="inline-block align-bottom bg-white rounded-lg px-4 pt-5 pb-4 text-left overflow-hidden shadow-xl transform transition-all sm:my-8 sm:align-middle sm:max-w-lg sm:w-full sm:p-6">
                    <div className="absolute top-0 right-0 pt-4 pr-4">
                        <button
                            type="button"
                            onClick={onClose}
                            className="bg-white rounded-md text-gray-400 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
                        >
                            <span className="sr-only">Close</span>
                            <X className="h-6 w-6" aria-hidden="true" />
                        </button>
                    </div>

                    <div className="sm:flex sm:items-start w-full">
                        <div className="mt-3 text-center sm:mt-0 sm:ml-4 sm:text-left w-full">
                            <h3 className="text-lg leading-6 font-medium text-gray-900">
                                {initialData ? 'Edit Item' : 'Add New Ledger Item'}
                            </h3>
                            <div className="mt-4">
                                <form onSubmit={handleSubmit} className="space-y-4">
                                    <div>
                                        <label htmlFor="date" className="block text-sm font-medium text-gray-700 text-left">Date</label>
                                        <input
                                            type="date"
                                            id="date"
                                            required
                                            value={date}
                                            onChange={(e) => setDate(e.target.value)}
                                            className="mt-1 block w-full border border-gray-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
                                        />
                                    </div>

                                    <div>
                                        <label htmlFor="category" className="block text-sm font-medium text-gray-700 text-left">Category</label>
                                        <select
                                            id="category"
                                            required
                                            value={category}
                                            onChange={(e) => setCategory(e.target.value)}
                                            className="mt-1 block w-full border border-gray-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
                                        >
                                            <option value="General">General</option>
                                            <option value="Tools">Tools</option>
                                            <option value="Parts">Parts</option>
                                            <option value="Labor">Labor</option>
                                            <option value="Materials">Materials</option>
                                            <option value="Plumbing">Plumbing</option>
                                            <option value="Electrical">Electrical</option>
                                            <option value="Structural">Structural</option>
                                            <option value="Interior">Interior</option>
                                        </select>
                                    </div>

                                    <div>
                                        <label htmlFor="item" className="block text-sm font-medium text-gray-700 text-left">Item / Service</label>
                                        <input
                                            type="text"
                                            id="item"
                                            required
                                            value={item}
                                            onChange={(e) => setItem(e.target.value)}
                                            placeholder="e.g. 3/4 Plywood Sheets"
                                            className="mt-1 block w-full border border-gray-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
                                        />
                                    </div>

                                    <div>
                                        <label htmlFor="vendor" className="block text-sm font-medium text-gray-700 text-left">Vendor</label>
                                        <input
                                            type="text"
                                            id="vendor"
                                            required
                                            value={vendor}
                                            onChange={(e) => setVendor(e.target.value)}
                                            placeholder="e.g. Home Depot"
                                            className="mt-1 block w-full border border-gray-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
                                        />
                                    </div>

                                    <div>
                                        <label htmlFor="cost" className="block text-sm font-medium text-gray-700 text-left">Cost</label>
                                        <div className="mt-1 relative rounded-md shadow-sm">
                                            <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                                                <span className="text-gray-500 sm:text-sm">$</span>
                                            </div>
                                            <input
                                                type="number"
                                                id="cost"
                                                required
                                                step="0.01"
                                                min="0"
                                                value={cost}
                                                onChange={(e) => setCost(e.target.value)}
                                                className="focus:ring-indigo-500 focus:border-indigo-500 block w-full pl-7 pr-12 sm:text-sm border-gray-300 rounded-md py-2"
                                                placeholder="0.00"
                                            />
                                        </div>
                                    </div>

                                    <div>
                                        <label className="block text-sm font-medium text-gray-700 text-left">Receipt</label>
                                        <div className="mt-1 flex justify-center px-6 pt-5 pb-6 border-2 border-gray-300 border-dashed rounded-md relative">
                                            <div className="space-y-1 text-center">
                                                <Upload className="mx-auto h-12 w-12 text-gray-400" />
                                                <div className="flex text-sm text-gray-600 justify-center">
                                                    <label
                                                        htmlFor="receipt-upload"
                                                        className="relative cursor-pointer bg-white rounded-md font-medium text-indigo-600 hover:text-indigo-500 focus-within:outline-none focus-within:ring-2 focus-within:ring-offset-2 focus-within:ring-indigo-500"
                                                    >
                                                        <span>Upload a file</span>
                                                        <input
                                                            id="receipt-upload"
                                                            name="receipt-upload"
                                                            type="file"
                                                            className="sr-only"
                                                            onChange={(e) => setFile(e.target.files ? e.target.files[0] : null)}
                                                        />
                                                    </label>
                                                </div>
                                                <p className="text-xs text-gray-500">
                                                    {file ? file.name : (initialData?.receipt_filename ? `Current: ${initialData.receipt_filename}` : 'PDF, PNG, JPG up to 10MB')}
                                                </p>
                                            </div>
                                        </div>
                                    </div>

                                    <div className="pt-4 sm:flex sm:flex-row-reverse">
                                        <button
                                            type="submit"
                                            disabled={isSubmitting}
                                            className="w-full inline-flex justify-center rounded-md border border-transparent shadow-sm px-4 py-2 bg-indigo-600 text-base font-medium text-white hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 sm:ml-3 sm:w-auto sm:text-sm disabled:opacity-50"
                                        >
                                            {isSubmitting ? (
                                                <>
                                                    <Loader2 className="animate-spin -ml-1 mr-2 h-4 w-4" />
                                                    Saving...
                                                </>
                                            ) : (
                                                initialData ? 'Save Changes' : 'Add Item'
                                            )}
                                        </button>
                                        <button
                                            type="button"
                                            disabled={isSubmitting}
                                            onClick={onClose}
                                            className="mt-3 w-full inline-flex justify-center rounded-md border border-gray-300 shadow-sm px-4 py-2 bg-white text-base font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 sm:mt-0 sm:ml-3 sm:w-auto sm:text-sm"
                                        >
                                            Cancel
                                        </button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
}
